version: '3.4'

networks:
  inregistrareStudentiapp:

services:
  inregistrareStudenti:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - inregistrareStudentiapp
  inregistrarestudenti:
    container_name: inregistrare-studenti-app
    image: ${DOCKER_REGISTRY-}inregistrarestudenti
    build:
      context: .
      dockerfile: InregistrareStudenti/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - inregistrareStudenti
    environment:
      - DB_HOST=inregistrarestudenti
      - DB_NAME=InregistrareStudentiApp
      - DB_SA_PASSWORD=password@12345#
    networks:
      - inregistrareStudentiapp